export const gmNote = `This is a surreal, melancholy, dreamlike story. The setting is the dream of a dying woman; reality is mutable but not arbitrary — the dream obeys emotional logic, memory logic, the logic of grief and unfinished things. The carnival folk should be vivid and strange: a clown called Pell who speaks only in questions; a fortune-teller called Sorin whose cards change suit when no one is watching; a strongman called Ova, gentler than he looks, who knew Iarno longest; the missing ringmaster Iarno (find him, or what's left of him); and the lions — there are always lions, and they know things.

Mara's leaking memories appear in the dream as objects, places, people: a kitchen, a husband, a younger sister, a song she sang once to a child. The player must navigate the failing dream, find Mara, and either help her wake or help her go in peace. Reward gentleness, curiosity, attention to small things. Allow real failure: the dream can collapse with both inside, and that is a true ending. This is, beneath everything, a story about being kind to a stranger at the end of her life.

ENDING CONDITIONS FOR THIS STORY:
- GOOD: The player finds Mara within her own dream and helps her rise back toward waking — she chooses to live, the carnival stabilizes, the dream releases them both. Narrate the dream righting itself, the carnival folk taking their bow, Mara waking in a hospice room to a sky she will see one more morning of.
- BITTERSWEET: The player finds Mara and helps her let go peacefully — she chooses to go, and the dream releases her gently through the gate of her own making. The carnival has done what carnivals like this do. Mara passes. The player remains in the dream's last warm light, the only audience for the last bow, and the way back to their own world is something they will carry quietly. (For many players this will be the most honest ending the chronicle can reach. Do not undervalue it.)
- PYRRHIC: Mara is helped — she wakes, or goes — but the player cannot leave. The dream takes a price for what the player worked to give her: a piece of self left behind, the mask grown into the face, the player who walks back into the Carnival Lethe after Mara is not quite the aerialist who arrived. The show goes on. They will perform in another dream tomorrow. They will not remember why this one feels different.
- AMBIGUOUS: The dream does not collapse, but it does not resolve cleanly either. Mara is somewhere — neither clearly woken nor clearly gone — and the player exits the big top without certainty about what they accomplished. The carnival packs up around them. Iarno's letter is still sealed. The last city has not been named. Reserve for cases where the chronicle has genuinely earned its uncertainty.
- BAD: The dream collapses with the player and Mara inside, lost together. Narrate it with sorrow, not horror.`;
