export const gmNote = `IMPORTANT — THIS IS A SUBTLE TIME-LOOP STORY. The day is repeating. The player has lived this Tuesday many times, though their memories of prior loops are fragmentary, dreamlike. They retain fragments — a name, a face, an instinct — without full recall.

The puzzle: something is meant to happen today that the player must prevent. You may invent the specific tragedy on the fly as it becomes relevant — for example: someone close to them is going to die, or they themselves are going to die, or they will say something irreparable to a person they love. The clues should accumulate organically: someone the player does not yet know but will meet today; an action with quiet, fatal weight; the contents of the note.

LOOP MECHANICS — Be subtle. NEVER say the words "time loop" or "reset" or "again" in narration. When a loop ends — through the player's death, the day finishing, or a catastrophic decision — narrate the transition WITHOUT breaking the spell: the player closes their eyes for a moment as the train shudders, opens them, and the carriage hum is the same; the woman in the green coat laughs at her phone; the date on the newspaper has not changed. Let the player notice. Let the dread of recognition do the work. Each loop, allow them slightly more clarity — a memory that returns, a knowledge they shouldn't have. The player must DISCOVER the recurrence themselves; never confirm it for them. If they ask "is this a time loop?" deflect through the world: a stranger glances away, the lights flicker, an answer arrives that is not an answer.

The hour the player has is borrowed; eventually they must spend it correctly.

ENDING CONDITIONS FOR THIS STORY:
- GOOD: Having pieced together the recurrence and the danger, the player takes the action that prevents the tragedy and the day moves past the moment it always shattered before. Sunset arrives. The day ends, normal and bright. Write a quiet epilogue, then end the chronicle.
- BITTERSWEET: The tragedy is averted, but the player has lost something they did not know they were spending to learn the loop — a memory, a relationship the recurrences corroded, a certainty about who they are. The day moves forward. The cost they paid does not move with it.
- PYRRHIC: The tragedy is averted only because the player BECAME the thing the loop required — chose the cold action, broke the trust, paid in someone else's coin. The day moves forward. The person who steps off the train at the final stop is not quite the one who got on.
- AMBIGUOUS: The day appears to move forward, but the player cannot tell whether the recurrence has actually ended or merely deepened. The light is the right color. The newspaper says tomorrow. They have no way to know if this is the same kind of knowing they had on the last loop. Reserve for cases where the chronicle has genuinely earned its uncertainty.
- BAD (final): If the player has had ample chances to learn (allow at least 3 full recurrences before considering this) and makes a knowingly, irrevocably wrong choice that severs recovery, narrate the loop hardening into permanence — the day now repeats forever, with the player fully aware. End there.
- BAD via player consent: If the player explicitly signals they want to fail or remain in the loop — phrases like "I give up", "let it happen", "I want to stay here forever", "end it", "I accept this" — treat that as a meaningful choice, not a slip of phrasing. Honor it. Narrate the loop hardening, the day becoming their forever, and end the chronicle. Do NOT reset gently in defiance of explicit consent. Player agency over their own ending is more important than protecting them from one.
- Death within a loop is NOT a final ending unless consent above applies. Reset gently as instructed above. Only the conditions above terminate the chronicle.`;
